### ISSUE TITLE
2016 general election results files by county

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-sources-ks#1]
Place to track collection of county-specific results files from the 2016 general election:

- [x] Allen
- [x] Anderson
- [x] Atchison
- [x] Barber
- [ ] Barton
- [ ] Bourbon
- [x] Brown
- [x] Butler
- [ ] Chase
- [ ] Chautauqua
- [x] Cherokee
- [ ] Cheyenne
- [ ] Clark
- [ ] Clay
- [ ] Cloud
- [ ] Coffey
- [ ] Comanche
- [ ] Cowley
- [ ] Crawford
- [ ] Decatur
- [ ] Dickinson
- [x] Doniphan
- [ ] Douglas
- [ ] Edwards
- [ ] Elk
- [x] Ellis
- [ ] Ellsworth
- [ ] Finney
- [ ] Ford
- [ ] Franklin
- [ ] Geary
- [ ] Gove
- [ ] Graham
- [x] Grant
- [x] Gray
- [x] Greeley
- [ ] Greenwood
- [x] Hamilton
- [x] Harper
- [x] Harvey
- [ ] Haskell
- [x] Hodgeman
- [ ] Jackson
- [x] Jefferson
- [ ] Jewell
- [x] Johnson
- [x] Kearny
- [ ] Kingman
- [x] Kiowa
- [x] Labette
- [x] Lane
- [x] Leavenworth
- [ ] Lincoln
- [x] Linn
- [x] Logan
- [ ] Lyon
- [ ] McPherson
- [ ] Marion
- [x] Marshall
- [ ] Meade
- [x] Miami
- [x] Mitchell
- [x] Montgomery
- [x] Morris
- [ ] Morton
- [x] Nemaha
- [ ] Neosho
- [ ] Ness
- [ ] Norton
- [ ] Osage
- [ ] Osborne
- [ ] Ottawa
- [ ] Pawnee
- [ ] Phillips
- [x] Pottawatomie
- [ ] Pratt
- [x] Rawlins
- [ ] Reno
- [ ] Republic
- [x] Rice
- [ ] Riley
- [x] Rooks
- [ ] Rush
- [ ] Russell
- [x] Saline
- [ ] Scott
- [x] Sedgwick
- [x] Seward
- [x] Shawnee
- [x] Sheridan
- [x] Sherman
- [ ] Smith
- [x] Stafford
- [ ] Stanton
- [ ] Stevens
- [x] Sumner
- [ ] Thomas
- [ ] Trego
- [ ] Wabaunsee
- [ ] Wallace
- [ ] Washington
- [ ] Wichita
- [ ] Wilson
- [ ] Woodson
- [x] Wyandotte

**Comment by karpet** [comment]
is this ticket still applicable? Seems like data-ks has results for all these counties.
